# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a1e2d5c3fef958dffa5c593e554ff7df961980c92293e299c94da6639d03917c7594bb1230b12584439c74288b97d1800e76b92ded1d6e5488150705792928b

test:
  secret_key_base: 08b95b726090b95b5e5ed1e0d50c1964f8b369ccedcf9c125a729d7ecc0330b74f455d6b59ae2cdd41db88cf03aa29207f0957e2b33579f289943ef29284f2a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
